// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import { PRODUCT_IDS } from '../mocks/mock-seed.js';
import type { Product } from '../schemas/product.schema.js';

export const PRODUCTS: Product[] = [
  {
    id: PRODUCT_IDS.ORG_DASHBOARD,
    name: 'Organization Dashboard',
    slug: 'organization-dashboard',
    description: 'Measure your impact across Linux Foundation projects.',
    iconUrl: '/assets/products/org-dashboard.svg',
    faIcon: 'fa-duotone fa-building',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.INDIVIDUAL_DASHBOARD,
    name: 'Individual Dashboard',
    slug: 'individual-dashboard',
    description: 'Track and share your achievements.',
    iconUrl: '/assets/products/individual-dashboard.svg',
    faIcon: 'fa-duotone fa-id-badge',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.PCC,
    name: 'Project Control Center',
    slug: 'project-control-center',
    description: 'Manage your project operations and governance.',
    iconUrl: '/assets/products/pcc.svg',
    faIcon: 'fa-duotone fa-bars-progress',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.SECURITY,
    name: 'Security',
    slug: 'security',
    description: 'Secure your project dependencies and code.',
    iconUrl: '/assets/products/security.svg',
    faIcon: 'fa-duotone fa-shield-halved',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.EASYCLA,
    name: 'EasyCLA',
    slug: 'easycla',
    description: 'Make contributing easy with automated CLA workflows.',
    iconUrl: '/assets/products/easycla.svg',
    faIcon: 'fa-duotone fa-file-contract',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.INSIGHTS,
    name: 'Insights',
    slug: 'insights',
    description: 'Gain deep analytics into your open source project health.',
    iconUrl: '/assets/products/insights.svg',
    faIcon: 'fa-duotone fa-chart-mixed',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.MENTORSHIP,
    name: 'Mentorship',
    slug: 'mentorship',
    description: 'Develop diverse talent through mentorship programs.',
    iconUrl: '/assets/products/mentorship.svg',
    faIcon: 'fa-duotone fa-hand-holding-heart',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.CROWDFUNDING,
    name: 'Crowdfunding',
    slug: 'crowdfunding',
    description: 'Support open technologies through transparent funding.',
    iconUrl: '/assets/products/crowdfunding.svg',
    faIcon: 'fa-duotone fa-chart-pie',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: PRODUCT_IDS.COMMUNITY_DATA,
    name: 'Community Data Platform',
    slug: 'community-data-platform',
    description: 'Collect and manage community data.',
    iconUrl: '/assets/products/community-data.svg',
    faIcon: 'fa-duotone fa-users',
    isActive: true,
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
];
