// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

import type { Product } from '../interfaces/product.interface.js';

export const PRODUCTS: Product[] = [
  {
    id: 'prod-org-dashboard',
    name: 'Organization Dashboard',
    slug: 'organization-dashboard',
    description: 'Measure your impact across Linux Foundation projects.',
    iconUrl: '/assets/products/org-dashboard.svg',
    faIcon: 'fa-duotone fa-building',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-individual-dashboard',
    name: 'Individual Dashboard',
    slug: 'individual-dashboard',
    description: 'Track and share your achievements.',
    iconUrl: '/assets/products/individual-dashboard.svg',
    faIcon: 'fa-duotone fa-id-badge',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-pcc',
    name: 'Project Control Center',
    slug: 'project-control-center',
    description: 'Manage your project operations and governance.',
    iconUrl: '/assets/products/pcc.svg',
    faIcon: 'fa-duotone fa-bars-progress',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-security',
    name: 'Security',
    slug: 'security',
    description: 'Secure your project dependencies and code.',
    iconUrl: '/assets/products/security.svg',
    faIcon: 'fa-duotone fa-shield-halved',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-easycla',
    name: 'EasyCLA',
    slug: 'easycla',
    description: 'Make contributing easy with automated CLA workflows.',
    iconUrl: '/assets/products/easycla.svg',
    faIcon: 'fa-duotone fa-file-contract',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-insights',
    name: 'Insights',
    slug: 'insights',
    description: 'Gain deep analytics into your open source project health.',
    iconUrl: '/assets/products/insights.svg',
    faIcon: 'fa-duotone fa-chart-mixed',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-mentorship',
    name: 'Mentorship',
    slug: 'mentorship',
    description: 'Develop diverse talent through mentorship programs.',
    iconUrl: '/assets/products/mentorship.svg',
    faIcon: 'fa-duotone fa-hand-holding-heart',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-crowdfunding',
    name: 'Crowdfunding',
    slug: 'crowdfunding',
    description: 'Support open technologies through transparent funding.',
    iconUrl: '/assets/products/crowdfunding.svg',
    faIcon: 'fa-duotone fa-chart-pie',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
  {
    id: 'prod-community-data',
    name: 'Community Data Platform',
    slug: 'community-data-platform',
    description: 'Collect and manage community data.',
    iconUrl: '/assets/products/community-data.svg',
    faIcon: 'fa-duotone fa-users',
    githubInstallationId: null,
    createdAt: '2024-01-01T00:00:00.000Z',
    updatedAt: '2024-01-01T00:00:00.000Z',
  },
];
