// Copyright The Linux Foundation and each contributor to LFX.
// SPDX-License-Identifier: MIT

// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import { buildConnectionString } from './src/server/helpers/build-connection-string';

// Tolerate missing DB env vars at config load so `prisma generate` (run from postinstall
// during CI/fresh installs) succeeds without real credentials. Migrate/seed/db-push
// surface the real requirement when they attempt to connect.
function resolveDatasourceUrl(): string {
  try {
    return buildConnectionString();
  } catch {
    return 'postgresql://unset:unset@localhost:5432/unset';
  }
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
    seed: 'yarn tsx prisma/seed.ts',
  },
  datasource: {
    url: resolveDatasourceUrl(),
  },
});
